### ISSUE TITLE
Allow for Roll data to be sent over Opentrack UDP

### ISSUE THREAD

**Issue by Juspertinry** [iVideoGameBoss/PhoenixHeadTracker#12]
When trying to use the software in conjunction with something such as SteamVR we are missing an output to use Roll. It seems to be exposed as evidenced by the GUI, just not made available.

**Comment by iVideoGameBoss** [comment]
Yeah so the thing with roll data is that all though AirAPI_Windows DLL is giving us access to it, we can't really do much with it. If you tilt your glasses and hold them for few seconds you will see the roll data is getting reset by the glasses themself. This is not a flaw in glasses but how the gyro is working. The issue is XREAL company knows how to handle roll data from these glasses. They are selling the XREAL Beam for $100 and it knows how to handle the resetting of roll data. They just won't give us access to the API, so this is why we have to use  AirAPI_Windows DLL which XREAL didn't approve. All I can do is get the degrees from this DLL and at least use Pitch and Yaw.

I've even used chatGPT to help me with this issue with sensor roll data getting reset in real world, so far no luck. chatGPT doesn't know how to handle this issue. I was thinking maybe a virtual gyro would do it but who knows.

You can download the code and turn on the roll data GUI in Visual Studio 2022 if you want to use roll data with OpenTrack UDP. I always had the GUI but just turn it off cause of the reset issue

![Screenshot 2024-02-04 170003](https://github.com/iVideoGameBoss/PhoenixHeadTracker/assets/129109589/c8d2d0ef-5eaf-4079-9df2-90e47c3fa76a)

mark it as true to use it in OpenTrack

**Comment by Juspertinry** [comment]
Ah, that is unfortunate but understandable. Thank you for the information.

**Comment by iVideoGameBoss** [comment]
roll data now works in latest release
