### ISSUE TITLE
Feature request: quick center. 

### ISSUE THREAD

**Issue by kingjamez** [iVideoGameBoss/PhoenixHeadTracker#5]
I’m not really sure how to implement this since the focus of the keyboard / joystick will be on the game, but it would be nice if there was a way to reset the center point with a button push after it drifts over time. The filters work great but ultimately I think the hardware will force resets after any long period. Right now, I have to pause the game, switch to Phoenix, then switch back to the game. I’m playing Condor 2 through OpenTrack. 

Ideally it would be a joystick button but specific keyboard combinations would work too.

**Comment by iVideoGameBoss** [comment]
This issue has been fixed in new release of PhoenixHeadTracker 3.0.3.3. I removed the Reset Rotation button as it is not needed and was causing confusion. Since you can rotate 360 degrees it is not necessary to keep resetting the rotation in PhoenixHeadTracker. Opentrack controls how the head moves inside the game so they have given users the ability to set up a center rotation key. I have included the instructions on how to do this in Opentrack and here also https://github.com/iVideoGameBoss/PhoenixHeadTracker. But I will include the screenshot here for you. So now when you are playing a game and need to re-center , you can click on your key in-game and opentrack will reset the center to new position. 3dof data as a 'whole system' will tend drift when you turn your head left to right a lot. Its the nature of physics. 

![Screenshot 2023-04-13 103644](https://user-images.githubusercontent.com/129109589/232177879-ec4c3a10-8a69-427e-8c10-f8dff4f335a2.png)
